#!/bin/bash

echo -e "1-Japanese\n2-german"
read -p "select your choice: " choice

if [ $choice -eq 1 ]
then
	for i in Toyota honda nissan
	do
		echo $i
done
elif [ $choice -eq 2 ]
then
	for i in  Mercedes BMW Audi
do
	echo $i
done
 

fi
 
 

	








